service: webhook-shopify
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  handler:
    handler: handler.handler
    events:
     - http:
         path: /
         method: get

plugins:
  - serverless-offline
  - serverless-webpack